### ISSUE TITLE
PTT

### ISSUE THREAD

**Issue by Meatballs1** [gentilkiwi/mimikatz#100]
Creating a golden ticket, and injecting it with /ptt I get a number of problems:

klist shows normal output

```
Current LogonId is 0:0x46f92

Cached Tickets: (1)

#0>     Client: @
        Server: krbtgt/
        KerbTicket Encryption Type: RSADSI RC4-HMAC(NT)
        Ticket Flags 0x40e00000 -> forwardable renewable initial pre_authent
        Start Time: 9/14/2017 14:08:47 (local)
        End Time:   9/12/2027 14:08:47 (local)
        Renew Time: 9/12/2027 14:08:47 (local)
        Session Key Type: RSADSI RC4-HMAC(NT)
        Cache Flags: 0x1 -> PRIMARY
        Kdc Called:

```

However typing klist tgt gives the following crash:

![image](https://user-images.githubusercontent.com/1854557/30431969-227eacfa-9958-11e7-8ef2-48724612adfb.png)

Win10 x64 - I also went into secpol.msc and enabled all the encryption types

**Comment by gentilkiwi** [comment]
In fact, this is a problem in the klist client ;) It does not handle very well its own Microsoft Kerberos API when there is some data missing in the structure.
Here, the KDC called... but it is of course not present in a normal Keberos ticket transport structure.

Generated by mimikatz or not, a "kirbi" file will be problematic (sometimes) with klist.
That's why I made a "kerberos::list" command too :)

**Comment by Meatballs1** [comment]
I wasn't sure if it was affecting my ability to auth - although I think my main issue is 'CLDAP' UDP packets being used by Windows/Kekeo when I'm sending everything over a proxy. Might need to hardcode some Kerberos settings on the Windows machine so it doesn't try CLDAP (RootDSE Query?)

**Comment by gentilkiwi** [comment]
I'm sorry to have missed your message (you've full access to my PM you know!) - there are option in registry to override KDC (and some LDAP req/discovery).
But usualy the problem is DNS, DNS & DNS ;)
