### ISSUE TITLE
I want to dump a lsass file while on a linux system.

### ISSUE THREAD

**Issue by sho-luv** [gentilkiwi/mimikatz#110]
What windows libraries would one need to have in order to parse an lsass.dump gained from windows. On a linux box. ... 

So I want to use wine to run mimikatz using winetricks on a linux system. To parse a LSASS dump I got from a windows box. 

Steps -> get on windows box -> dump lsass process -> get dump to linux box -> run mimikatz with wine to parse dump...

<img width="1157" alt="screen shot 2017-11-14 at 7 11 19 pm" src="https://user-images.githubusercontent.com/1679089/32816847-acef6fd6-c96f-11e7-9567-d4175f4baf97.png">

Is this possible? 
What is this line of code checking for? LocalLib() ... Basically can I get winetricks to pass this check is my question to you.

My Error:
ERROR kuhl_m_sekurlsa_acquireLSA ; Local LSA library failed

Traced back to this line of code I think:

```
mimikatz/mimikatz/modules/sekurlsa/kuhl_m_sekurlsa.c

243 		if(NT_SUCCESS(lsassLocalHelper->initLocalLib()))

```

**Comment by gentilkiwi** [comment]
`mimikatz` hardly relies on Windows subsystem... not sure Wine emulate all the necessary.
We are in 2018, I can't think security teams don't use a VM for all the Windows good stuff :)

**Comment by cooperfrench95** [comment]
> `mimikatz` hardly relies on Windows subsystem... not sure Wine emulate all the necessary.
> We are in 2018, I can't think security teams don't use a VM for all the Windows good stuff :)

Have you installed a windows VM lately? Say goodbye to 100gb of hard drive space and half your ram. Nobody wants to do that if they can avoid it.

**Comment by gentilkiwi** [comment]
Yep, I do it on a regular basis for mimikatz regression tests by eg:

`09/06/2020  23:03    13 660 848 128 windows_10_2004_enterprise_x64.vhdx`

It seems you don't, cause 13 GB of disk (and 2 GB of memory) for a full up to date W10 x64 is not a lot...

The local LSA lib was certainly due to a NT5 dump file (an XP SP3 full up to date disk is 10 GB by the way), since this commit: https://github.com/gentilkiwi/mimikatz/commit/4d4d047b50c9869fac30016b55751bb8048445ba#diff-33e4c330c6301349fc02c5774e05ad12 it does not rely on lsasrv.dll anymore
