### ISSUE TITLE
ccache to kirbi file parser for Linux

### ISSUE THREAD

**Issue by Thanathan-k** [gentilkiwi/mimikatz#15]
Since Mimikatz is able to inject the ccache files generated in Linux, would it be possible to write a parser that can run under Linux to generate .kirbi files from the ccache file? I've tried to look into the code (kuhl_m_kerberos_ccache), but since nothing is commented I'm having a hard time to get into it.

**Comment by jun0s** [comment]
https://github.com/rvazarkar/KrbCredExport

**Comment by gentilkiwi** [comment]
If you read Python (not like me ;)), please, take a look at @jun0s like.

In all case, no magical tricks in tools, all is based on:
* https://www.gnu.org/software/shishi/manual/html_node/The-Credential-Cache-Binary-File-Format.html
* https://tools.ietf.org/html/rfc1510#section-5.8.1

With a little bit of ASN.1 inside ;)

Otherwise, you can have a look inside `kekeo`, especially the `kirbikator` project : https://github.com/gentilkiwi/kekeo/tree/master/kirbikator
Its goal is to convert from everything, to everything... (convert, split, merge, etc... from different formats).

More understandable than `mimikatz` because `kekeo` uses small code dedicated to Kerberos.

**Comment by jun0s** [comment]
I forgot kekeo -.-´ but he say "under linux"

**Comment by gentilkiwi** [comment]
I only mention it because of the code ;)

**Comment by Thanathan-k** [comment]
Thank you guys! I'll have a look at the python project, as well as the provided links to get some more understanding of the topic :)
