### ISSUE TITLE
Possible execution with unnecessary privileges [Vulnerability Hits]

### ISSUE THREAD

**Issue by jishanshaikh4** [gentilkiwi/mimikatz#355]
If this call fails, the program could fail to drop heightened privileges.

LABEL: Bug
SEVERITY: Major
SOLUTION: Make sure the return value is checked, and do not continue if a failure is reported.
COMMON WEAKNESS ENUMERATION INDEX: CWE-250

Instances found in the GitHub repository:
- [ ] mimikatz\modules\sekurlsa\kuhl_m_sekurlsa.c:979
- [ ] modules\rpc\kull_m_rpc.c:138 
- [ ] mimikatz\modules\kuhl_m_token.c:316
- [ ] mimikatz\modules\kuhl_m_token.c:143
- [ ] mimikatz\modules\dpapi\packages\kuhl_m_dpapi_ssh.c:188 
- [ ] mimikatz\modules\dpapi\packages\kuhl_m_dpapi_ssh.c:181

**Comment by gentilkiwi** [comment]
Hi @jishanshaikh4 

Could you please explain why do you understand of your own message? And what is exactly the problem behind?

If you just push issues because you ran an automated scan of tools* you did not understood, please, stop it. It's embarassing for both of us (but not really for me)

> *By eg, like with this (excelent) tool from @david-a-wheeler : https://dwheeler.com/flawfinder/ / https://github.com/david-a-wheeler/flawfinder

PS: impressive
![image](https://user-images.githubusercontent.com/2307945/123172712-cc636a80-d47d-11eb-8838-157273900602.png)

**Comment by jishanshaikh4** [comment]
Acknowledging the issue is your concern, I just found an issue (Right, by flawfinder) and reported it. I'm just an open-source "contributor", you are the owner, it's your discreet to pursue it. 

There is nothing to be embarrassed about.

PS: About 139 issues, most of them were created by bots to notify me about "issues".
