### ISSUE TITLE
DCSync returns an incorrect LM hash if there is no LM hash at the DC

### ISSUE THREAD

**Issue by jmvdbreekel** [gentilkiwi/mimikatz#77]
I experienced the following behaviour at two completely different client engagements:

Using the DCSync command I was able to retrieve LM and NT hashes for specific accounts after I became domain administrator. However, the LM hash returned by DCSync was not actual the LM hash of the password, and as of now I was not able to figure what it actually was (it was also not the null-LM hash, and the LM hashes were different for different accoutns). The returned NT hash, however, was indeed the NT hash of the plaintext password. 

Both client companies had LM hashing disabled for all their DCs. We verified this by changing the password of accounts and dumping the NTDS.dit file. No new LM hashing were created for new accounts or for existing accounts that changed their password.

So my current theory is that if storing LM hashing is disabled for a domain and LM hashes are not available for certain accounts, DCSync will still return (seemingly) random LM hashes when used.

BTW, we are a huge fan of your project and it is a big help for our engagements for many of our clients. Your work is greatly appreciated!

**Comment by MichaelGrafnetter** [comment]
Hi @jmvdbreekel, aren't you just misinterpreting the results? Below is a sample DCSync output, containing the current NTLM hash from the unicodePwd attribute, 3 historical NTLM hashes from the ntPwdHistory attribute and 2 historical LM hashes from the lmPwdHistory attribute. Because storing LM hashes is disabled on that DC, the dBCSPwd attribute is empty and mimikatz does not display it. Moreover, the historical LM hashes are randomly generated during each password change, for some strange reason.

![DCSync Sample](https://adsecurity.org/wp-content/uploads/2015/09/Mimikatz-DCSync-UserRights-DCR-Administrator-500-Dump2.jpg)

**Comment by jmvdbreekel** [comment]
Dear @MichaelGrafnetter , apparently I was misinterpreting the results and I'm sorry about this unnecessarily opened issue. I was not aware that historical LM hashes would be generated randomly by the DC itself. For more information (in case anyone ever reaches this issue), check this site: https://labs.mwrinfosecurity.com/blog/when-lanman-history-reveals-the-present-and-future-but-might-just-be-lying-to-you/
