### ISSUE TITLE
Typo in Wiki page

### ISSUE THREAD

**Issue by DavidMetcalfe** [gentilkiwi/mimikatz#89]
https://github.com/gentilkiwi/mimikatz/wiki/module-~-lsadump

"Volue Shadow Copy" should be "Volume Shadow Copy"

**Comment by BeanBagKing** [comment]
I'll add this here, since it is also a typo on the same page and I don't believe it worth adding a new issue.

`mimikatz # lsadump::sam SystemBkup.hiv SamBkup.hiv `

should be 

`mimikatz # lsadump::sam /system:SystemBkup.hiv /sam:SamBkup.hiv`

Per this thread: https://github.com/gentilkiwi/mimikatz/issues/80

**Comment by gentilkiwi** [comment]
Fixed in Wiki :)
